spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        druid:
            # 运行库
            run:
                url: jdbc:sqlserver://172.16.0.227:1433;DatabaseName=emwx_run
                username: sa
                password: sa123456.123
            # 配置库
            config:
                enabled: true
                url: jdbc:sqlserver://172.16.0.227:1433;DatabaseName=emwx_dispose
                username: sa
                password: sa123456.123
            # 模板库
            module:
                enabled: true
                url: jdbc:sqlserver://172.16.0.227:1433;DatabaseName=emwx_dispose
                username: sa
                password: sa123456.123
            erp:
                enabled: true
                url: jdbc:sqlserver://172.16.0.234:1433;DatabaseName=hella_dispose1
                username: sa
                password: sa123456.123
            # 初始连接数
            initial-size: 10
            # 最大连接池数量
            max-active: 100
            # 最小连接池数量
            min-idle: 10
            # 配置获取连接等待超时的时间
            max-wait: 60000
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            filters: stat,wall,log4j
            stat-view-servlet:
                enabled: true
                url-pattern: /monitor/druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
